### ISSUE TITLE
don't push buggy code to master

### ISSUE THREAD

**Issue by petigura** [jvanzand/trends#15]
master branch should contain a working version of the code. 

```
[trends]$ python setup.py build_ext --inplace
Compiling c_kepler/_kepler.pyx because it changed.
Compiling trends/helper_functions_wrapper.pyx because it changed.
[1/2] Cythonizing c_kepler/_kepler.pyx
[2/2] Cythonizing trends/helper_functions_wrapper.pyx

Error compiling Cython file:
------------------------------------------------------------
...
au = 14959787070000.0

hip_times  = [2447837.75, 2449065.15]
gaia_times = [2456863.5, 2457531.5]

<<<<<<< HEAD
^
------------------------------------------------------------

trends/helper_functions_wrapper.pyx:48:0: Expected an identifier or literal
Traceback (most recent call last):
  File "/Users/petigura/code/trends/setup.py", line 36, in <module>
    ext_modules = cythonize(extensions, language_level='3', annotate=True)
  File "/Users/petigura/miniconda3/envs/trends_env/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/Users/petigura/miniconda3/envs/trends_env/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: trends/helper_functions_wrapper.pyx
```

**Comment by jvanzand** [comment]
👍
